// playground/App.vue
<script setup lang='ts'>
import { useRouter } from 'vue-router'
</script>

<template>
  <div>
    <MySvgIcon name="icon-common-logo" style="margin-right: 20px;" />
    <MySvgIcon name="icon-logo" style="margin-right: 20px;" />
    <MySvgIcon name="icon-icon-addUser" style="margin-right: 20px;" />
    <MySvgIcon name="icon-icon-card2" style="margin-right: 20px;" />
  </div>
</template>

<style scoped lang="scss">

</style>

// examples/react-vite/src/App.tsx
import './App.css'
import MySvgIcon from '~virtual/svg-component'

function App() {
  return (
    <div className="logo">
      <MySvgIcon name='icon-react'></MySvgIcon>
      <MySvgIcon name='icon-icon-card2'></MySvgIcon>
      <MySvgIcon name='icon-icon-addUser'></MySvgIcon>
    </div>
  )
}

export default App
